export const projectTypes = [
  { id: "landing", name: "Landing page", price: 3000, hint: "Uma página focada em uma oferta", description: "Página única com conteúdo organizado para apresentar um serviço, campanha ou produto.", why: "Uma página precisa de estrutura, conteúdo e adaptação para diferentes telas. A estimativa considera um escopo inicial de página única.", includes: ["Estrutura de uma página", "Adaptação para celular e desktop", "Publicação do escopo combinado"], needed: "Quando você quer apresentar uma oferta ou serviço em uma página direta.", fallback: "O visitante não terá uma página própria com as informações organizadas." },
  { id: "institutional", name: "Site institucional", price: 4800, hint: "Sua empresa na internet", description: "Apresentação da empresa, serviços, canais de contato e informações institucionais.", why: "O valor inicial contempla uma estrutura básica para apresentar uma empresa. Conteúdo, páginas extras e recursos funcionais alteram o escopo.", includes: ["Estrutura inicial do site", "Uma página inicial", "Adaptação responsiva"], needed: "Quando você quer apresentar a empresa e seus serviços na internet.", fallback: "A empresa pode usar outros canais ou uma página simples com menos estrutura." },
  { id: "portfolio", name: "Portfólio", price: 3800, hint: "Trabalhos e apresentação", description: "Uma vitrine para apresentar projetos, experiência e formas de contato.", why: "É preciso organizar os trabalhos, apresentação e navegação numa estrutura visual coerente.", includes: ["Estrutura de apresentação", "Uma página inicial", "Adaptação responsiva"], needed: "Quando profissionais precisam apresentar projetos e experiência.", fallback: "Os trabalhos podem ficar apenas em plataformas externas." },
  { id: "blog", name: "Blog", price: 5800, hint: "Conteúdo organizado", description: "Site de conteúdo com estrutura para publicação e navegação por artigos.", why: "Um blog exige páginas para organizar e apresentar conteúdo; publicação administrável pode exigir banco e área administrativa.", includes: ["Estrutura inicial de conteúdo", "Uma página inicial", "Navegação básica"], needed: "Quando você quer publicar conteúdo em um endereço próprio.", fallback: "As publicações podem ficar em uma plataforma de terceiros." },
  { id: "ecommerce", name: "Loja virtual / e-commerce", price: 15000, hint: "Produtos e pedidos", description: "Loja com catálogo e fluxos de compra. Pagamentos e operação podem exigir serviços adicionais.", why: "Catálogo, carrinho e pedidos envolvem fluxos diferentes de um site informativo e costumam precisar de dados e integrações.", includes: ["Estrutura inicial da loja", "Uma página inicial", "Escopo detalhado na análise"], needed: "Quando você precisa apresentar produtos e receber pedidos pela internet.", fallback: "As vendas podem ocorrer em loja física ou plataforma externa." },
  { id: "webapp", name: "Sistema web", price: 18000, hint: "Regras e dados próprios", description: "Aplicação com fluxos interativos, lógica de negócio e possíveis áreas autenticadas.", why: "Sistemas interativos dependem das regras do negócio, da comunicação entre telas e serviços e do armazenamento de informações.", includes: ["Estrutura inicial da aplicação", "Uma tela inicial", "Análise dos requisitos específicos"], needed: "Quando o projeto precisa executar tarefas ou regras próprias online.", fallback: "As tarefas podem depender de processos manuais ou ferramentas diferentes." },
  { id: "admin", name: "Site com área administrativa", price: 9500, hint: "Conteúdo que você gerencia", description: "Site com uma área protegida para administrar conteúdo ou informações.", why: "Além do site público, a área administrativa precisa de acesso controlado e operações para alterar o conteúdo previsto.", includes: ["Estrutura inicial do site", "Uma página inicial", "Área administrativa conforme escopo"], needed: "Quando a equipe precisa administrar conteúdo sem editar arquivos do site.", fallback: "As atualizações podem exigir alteração técnica ou atendimento manual." },
  { id: "custom", name: "Projeto personalizado", price: 3000, hint: "Estimativa inicial", description: "Ponto de partida para conversar sobre requisitos que não cabem nos modelos prontos.", why: "Sem requisitos detalhados, este valor é apenas uma referência inicial; o projeto pode demandar outra estrutura.", includes: ["Referência de partida", "Análise dos requisitos em conversa", "Escopo definido antes da proposta"], needed: "Quando você precisa de uma solução que não se encaixa nos outros tipos.", fallback: "A estimativa pode ser ajustada após descrever melhor as necessidades." },
];

export const scenarios = [
  { id: "complete", name: "Projeto completo", detail: "Interface, páginas e recursos do projeto.", why: "Este modelo estima o desenvolvimento do projeto inteiro e permite escolher separadamente quais serviços recorrentes serão fornecidos.", includes: ["Tipo de projeto", "Páginas e funcionalidades selecionadas", "Infraestrutura escolhida à parte"], needed: "Quando você quer estimar também a interface e as páginas.", fallback: "Você pode escolher API e banco se já tiver uma interface própria.", billing: "Sem cobrança própria; define a base do escopo." },
  { id: "own-server", name: "Já tenho servidor", detail: "Infraestrutura que você já possui não entra por padrão.", why: "A opção retira hospedagem da aplicação e do banco gerenciado do cálculo. Desenvolvimento e serviços que você selecionar continuam estimados.", includes: ["Infraestrutura gerenciada desmarcada", "Desenvolvimento permanece no cálculo", "Possibilidade de selecionar outros serviços"], needed: "Quando você pretende usar uma hospedagem que já administra.", fallback: "Você pode selecionar infraestrutura gerenciada no configurador.", billing: "Sem cobrança própria; remove serviços gerenciados do cálculo." },
  { id: "api-only", name: "Somente API + banco", detail: "Para quem já tem site ou interface própria.", why: "Este cenário concentra a estimativa na lógica de backend e na estrutura de dados, sem calcular páginas ou interface do projeto.", includes: ["Estrutura inicial de API", "Backend e banco selecionados", "Infraestrutura selecionada separadamente"], needed: "Quando você já tem frontend ou pretende desenvolvê-lo separadamente.", fallback: "Você pode voltar ao projeto completo para incluir a interface.", billing: "Estimativa inicial de API; infraestrutura é opcional e separada." },
];

export const pages = [
  { id: "home", name: "Home", price: 0, kind: "simple", description: "Página inicial para apresentar o projeto e orientar a navegação." },
  { id: "about", name: "Sobre", price: 450, kind: "simple", description: "Conteúdo institucional, história, equipe ou apresentação do serviço." },
  { id: "services", name: "Serviços", price: 500, kind: "simple", description: "Organização e apresentação dos serviços oferecidos." },
  { id: "products", name: "Produtos", price: 700, kind: "simple", description: "Vitrine de produtos. Catálogo dinâmico e compra exigem funcionalidades adicionais." },
  { id: "contact", name: "Contato", price: 400, kind: "simple", description: "Informações e canais para o visitante entrar em contato." },
  { id: "faq", name: "FAQ", price: 350, kind: "simple", description: "Respostas organizadas para dúvidas frequentes." },
  { id: "blog", name: "Blog", price: 700, kind: "simple", description: "Página de listagem de conteúdo; publicação dinâmica pode exigir backend e banco." },
  { id: "login", name: "Login", price: 1300, kind: "functional", description: "Interface da tela. Autenticação e proteção são estimadas como funcionalidades." },
  { id: "registration", name: "Cadastro", price: 1200, kind: "functional", description: "Interface de cadastro. Regras de conta e armazenamento são estimadas à parte." },
  { id: "recovery", name: "Recuperação de senha", price: 1000, kind: "functional", description: "Interface do fluxo. Tokens e envio de e-mail são estimados como funcionalidades." },
  { id: "dashboard", name: "Painel administrativo", price: 1800, kind: "functional", description: "Estrutura visual do painel. Acesso e operações são estimados como funcionalidades." },
  { id: "custom-page", name: "Página personalizada", price: 900, kind: "simple", description: "Uma página adicional com estrutura e conteúdo definidos para o projeto." },
];

export const features = [
  { id: "contact-form", group: "Interação", name: "Formulário de contato", price: 550, description: "Formulário com validações básicas para receber solicitações.", why: "A interface precisa validar os campos e encaminhar a mensagem com segurança. Se houver armazenamento, histórico ou notificações, o escopo aumenta.", includes: ["Campos e validações combinados", "Confirmação visual de envio", "Integração definida no escopo"], needed: "Quando visitantes precisam enviar informações sem sair do site.", fallback: "Sem ele, o visitante usa canais externos, como e-mail ou telefone." },
  { id: "login", group: "Contas e administração", name: "Sistema de login", price: 1600, description: "Autenticação para restringir áreas a pessoas autorizadas.", why: "Login não é só uma tela: envolve comunicação com backend, validação de credenciais, sessão e cuidados para proteger contas.", includes: ["Fluxo de autenticação combinado", "Validação de entradas", "Tratamento básico de estados e erros"], needed: "Quando conteúdos ou ações não devem ser públicos.", fallback: "Sem autenticação, não há acesso individual protegido." },
  { id: "registration", group: "Contas e administração", name: "Cadastro de usuários", price: 1200, description: "Criação de contas e validação dos dados informados.", why: "O sistema precisa validar informações e guardar a conta de forma apropriada, normalmente usando backend e banco de dados.", includes: ["Campos definidos para o cadastro", "Validação básica", "Integração com a estrutura de usuários"], needed: "Quando cada pessoa precisa ter uma conta própria.", fallback: "Contas podem precisar ser criadas manualmente ou o recurso não estará disponível." },
  { id: "password-recovery", group: "Contas e administração", name: "Recuperação de senha", price: 900, description: "Fluxo para recuperar acesso à conta com segurança.", why: "É preciso validar a solicitação, criar uma recuperação temporária e configurar a entrega das instruções.", includes: ["Fluxo de solicitação", "Validação do processo", "Integração de envio definida no projeto"], needed: "Quando usuários autenticados podem esquecer a senha.", fallback: "A recuperação pode exigir atendimento manual." },
  { id: "client-area", group: "Contas e administração", name: "Área do cliente", price: 2400, description: "Espaço autenticado com informações ou serviços individuais.", why: "Cada usuário precisa visualizar apenas seus próprios dados, o que envolve regras de acesso e integração com backend.", includes: ["Estrutura da área privada", "Conexão com dados previstos", "Controles básicos de acesso"], needed: "Quando o cliente precisa consultar informações ou executar ações após entrar.", fallback: "As informações podem ser atendidas por outros canais, sem autoatendimento." },
  { id: "admin-panel", group: "Contas e administração", name: "Painel administrativo", price: 2300, description: "Ferramentas internas para administrar o sistema.", why: "O painel precisa reunir operações administrativas e restringi-las às pessoas autorizadas.", includes: ["Telas para funções combinadas", "Acesso protegido", "Integração com os dados previstos"], needed: "Quando a equipe precisa alterar ou consultar dados sem editar código.", fallback: "As mudanças podem exigir operação manual ou suporte técnico." },
  { id: "permissions", group: "Contas e administração", name: "Níveis de permissão", price: 1400, description: "Define o que cada tipo de usuário pode acessar ou alterar.", why: "Cada ação precisa respeitar regras de acesso, tanto na interface como no backend.", includes: ["Perfis de acesso combinados", "Regras para ações previstas", "Testes básicos de permissão"], needed: "Quando usuários ou equipes têm responsabilidades diferentes.", fallback: "Todos podem ficar sujeitos ao mesmo conjunto de permissões." },
  { id: "file-upload", group: "Recursos de dados", name: "Envio de arquivos", price: 1100, description: "Permite anexar arquivos dentro de regras definidas.", why: "É necessário tratar formato, tamanho, armazenamento e controle de acesso aos arquivos.", includes: ["Fluxo de envio", "Validação de tipo e tamanho", "Destino de armazenamento definido"], needed: "Quando pessoas precisam enviar documentos, imagens ou outros arquivos.", fallback: "Os arquivos podem ser enviados por um canal externo." },
  { id: "database", group: "Recursos de dados", name: "Banco de dados", price: 1200, description: "Estrutura que guarda informações do sistema para uso futuro.", why: "Um banco é necessário para guardar usuários, produtos, pedidos, mensagens ou configurações. O desenvolvimento inclui modelar as estruturas e conectar o sistema; a hospedagem do banco é uma infraestrutura recorrente separada.", includes: ["Estrutura inicial de dados", "Integração com a aplicação", "Consultas e regras previstas", "Testes básicos de funcionamento"], needed: "Quando as informações precisam continuar salvas entre acessos.", fallback: "Sem banco, dados permanentes precisam ser mantidos em outro serviço ou deixam de ser persistidos." },
  { id: "search", group: "Recursos de dados", name: "Busca", price: 850, description: "Ajuda o visitante a localizar conteúdo ou registros.", why: "É preciso definir quais dados podem ser buscados e como apresentar resultados relevantes.", includes: ["Campo e apresentação de resultados", "Critérios combinados", "Integração com a fonte de dados"], needed: "Quando o volume de conteúdo torna a navegação manual difícil.", fallback: "A navegação fica limitada a menus, categorias ou filtros." },
  { id: "filters", group: "Recursos de dados", name: "Filtros", price: 750, description: "Permite refinar listas por critérios como tipo, preço ou data.", why: "Os critérios precisam ser conectados aos dados e funcionar em conjunto sem confundir quem usa.", includes: ["Filtros previstos no escopo", "Atualização da lista", "Comportamento responsivo"], needed: "Quando o usuário precisa encontrar itens em listas maiores.", fallback: "A lista pode ser exibida sem refinamento por critérios." },
  { id: "api-backend", group: "Integrações e automação", name: "API / backend próprio", price: 2800, description: "A lógica que processa informações e conecta partes do sistema.", why: "O frontend mostra a interface. O backend aplica regras, processa pedidos, conversa com o banco e pode expor APIs para outros serviços. Uma aplicação dinâmica costuma precisar de infraestrutura diferente de um site estático.", includes: ["Rotas e regras acordadas", "Validações no servidor", "Integração com o banco quando selecionado", "Testes básicos das operações"], needed: "Quando o site precisa processar regras, autenticar usuários ou servir dados dinâmicos.", fallback: "Sem backend próprio, recursos dinâmicos podem depender de serviços terceiros ou não existir." },
  { id: "payments", group: "Integrações e automação", name: "Pagamentos online", price: 2200, description: "Integração com um provedor para iniciar e acompanhar cobranças.", why: "Pagamento envolve integrar um serviço externo e tratar estados como aprovação, recusa e cancelamento. Tarifas do provedor não fazem parte deste desenvolvimento.", includes: ["Integração com provedor definido", "Tratamento dos estados previstos", "Testes em ambiente apropriado"], needed: "Quando o usuário precisa pagar dentro do fluxo digital.", fallback: "O pagamento pode ocorrer por outro canal, fora do sistema." },
  { id: "cart", group: "Integrações e automação", name: "Carrinho de compras", price: 1900, description: "Organiza itens escolhidos antes de concluir uma compra.", why: "O carrinho precisa manter os itens e quantidades e conectá-los ao processo de pedido.", includes: ["Inclusão e remoção de itens", "Resumo de quantidades e valores", "Integração prevista para o pedido"], needed: "Quando a loja oferece compra de vários itens em uma jornada.", fallback: "A compra pode ser feita por produto, sem carrinho compartilhado." },
  { id: "external-api", group: "Integrações e automação", name: "Integração com API externa", price: 1300, description: "Conecta o projeto a dados ou serviços de outro fornecedor.", why: "Cada serviço tem regras, formatos e limites próprios; a integração precisa transformar respostas e lidar com falhas.", includes: ["Conexão com serviço definido", "Tratamento básico de respostas", "Configuração sem expor credenciais"], needed: "Quando o projeto depende de um serviço externo.", fallback: "Os dados podem ser inseridos manualmente ou o recurso pode não estar disponível." },
  { id: "notifications", group: "Integrações e automação", name: "Notificações", price: 900, description: "Informa usuários sobre eventos relevantes do sistema.", why: "É necessário definir os eventos, destinatários e canais, além de evitar mensagens incorretas ou repetidas.", includes: ["Eventos e mensagens previstos", "Canal acordado", "Regras básicas de disparo"], needed: "Quando usuários precisam ser avisados sem acompanhar a página.", fallback: "A pessoa precisa verificar atualizações diretamente no sistema." },
  { id: "automated-email", group: "Integrações e automação", name: "E-mails automáticos", price: 800, description: "Envio de mensagens como confirmações e avisos do sistema.", why: "O conteúdo, o gatilho e o serviço de entrega precisam ser configurados. O provedor pode cobrar à parte.", includes: ["Modelos de mensagens definidos", "Gatilhos previstos", "Integração com serviço de e-mail"], needed: "Quando o sistema precisa confirmar ações ou enviar informações automaticamente.", fallback: "Mensagens podem precisar ser enviadas manualmente." },
  { id: "custom-integration", group: "Integrações e automação", name: "Integração personalizada", price: 1800, description: "Conecta processos específicos que não estão nos modelos comuns.", why: "O trabalho depende dos sistemas envolvidos, das regras e da disponibilidade de documentação técnica.", includes: ["Análise da integração combinada", "Fluxo de dados definido", "Teste básico da comunicação"], needed: "Quando seu processo exige conexão entre ferramentas específicas.", fallback: "As informações podem ser transferidas manualmente." },
  { id: "logs", group: "Operação e acompanhamento", name: "Registros de atividade", price: 700, description: "Mantém histórico técnico de eventos selecionados.", why: "É preciso definir o que registrar, por quanto tempo e quem pode consultar esses registros.", includes: ["Eventos básicos definidos", "Registro estruturado", "Retenção inicial combinada"], needed: "Quando há necessidade de investigar operações e erros.", fallback: "A investigação fica limitada a mensagens técnicas disponíveis no momento." },
  { id: "backups", group: "Operação e acompanhamento", name: "Rotina de backups", price: 600, monthly: 45, description: "Cópias de segurança para ajudar na recuperação de dados.", why: "É preciso automatizar cópias, definir retenção e verificar que os arquivos possam ser recuperados. Armazenamento e operação podem ser recorrentes.", includes: ["Rotina inicial de cópia", "Retenção acordada", "Orientação básica de recuperação"], needed: "Quando é importante recuperar dados após falhas ou alterações indesejadas.", fallback: "A recuperação pode ser limitada ao que o provedor de infraestrutura oferece." },
  { id: "analytics", group: "Operação e acompanhamento", name: "Analytics", price: 500, description: "Mede visitas e interações conforme ferramentas configuradas.", why: "A ferramenta precisa ser configurada e os eventos relevantes definidos, respeitando as escolhas de privacidade do site.", includes: ["Configuração da ferramenta definida", "Métricas básicas", "Eventos acordados"], needed: "Quando você quer acompanhar uso e desempenho do site.", fallback: "Você terá menos dados sobre visitas e interações." },
];

export const infrastructure = [
  { id: "hosting", name: "Hospedagem gerenciada", price: 120, unit: "mês", description: "Mantém o projeto disponível na internet; a estrutura depende do tipo de aplicação.", why: "Um servidor ou serviço de hospedagem entrega o projeto aos visitantes. Sistemas dinâmicos podem precisar de recursos específicos, como execução de backend e armazenamento.", includes: ["Publicação do projeto contratado", "Recursos definidos para a aplicação", "Operação conforme o serviço contratado"], needed: "Quando você quer que a hospedagem seja fornecida no mesmo modelo de contratação.", fallback: "Você pode contratar e administrar uma hospedagem compatível por conta própria." },
  { id: "database-hosting", name: "Hospedagem de banco de dados", price: 85, unit: "mês", description: "Serviço gerenciado para armazenar os dados da aplicação.", why: "Além de desenvolver e conectar o banco, é necessário manter o serviço disponível, com armazenamento e recursos compatíveis. A cobrança recorrente é separada da criação do banco.", includes: ["Instância inicial conforme o projeto", "Armazenamento contratado", "Serviço disponível conforme o fornecedor"], needed: "Quando o banco será hospedado em um serviço fornecido neste modelo.", fallback: "Você pode usar um banco gerenciado por conta própria ou manter o banco na infraestrutura que já administra." },
  { id: "domain", name: "Registro e gerenciamento de domínio", price: 65, unit: "ano", description: "Endereço público do projeto, como exemplo.com.br. Valor de referência anual.", why: "O domínio é registrado em um fornecedor e precisa ser renovado periodicamente. O preço e a disponibilidade dependem do nome escolhido e do registrador.", includes: ["Orientação inicial para registro", "Configuração de apontamento quando contratada", "Renovação paga ao registrador"], needed: "Quando você quer um endereço próprio para acessar o projeto.", fallback: "O projeto pode usar um endereço fornecido pela plataforma de hospedagem." },
];

export const maintenance = [
  { id: "maintenance", name: "Manutenção periódica", price: 280, unit: "mês", description: "Pequenas correções, verificações e atualizações acordadas.", why: "A manutenção reserva tempo para acompanhar atualizações e tratar solicitações dentro de um limite combinado.", includes: ["Verificações periódicas", "Pequenas correções previstas", "Atualizações conforme compatibilidade"], needed: "Quando você prefere ter apoio contínuo para ajustes e verificações.", fallback: "Você pode administrar e contratar intervenções quando necessário." },
  { id: "emergency", name: "Atendimento emergencial", price: 450, unit: "chamado", description: "Estimativa por chamado prioritário fora do fluxo normal.", why: "Intervenções prioritárias exigem reorganizar agenda e investigar problemas com urgência. O valor final depende da situação.", includes: ["Triagem prioritária", "Investigação inicial", "Alinhamento de próximos passos"], needed: "Quando um problema precisa de atenção prioritária.", fallback: "O atendimento segue o prazo e o canal de suporte padrão." },
];

export const delivery = {
  id: "delivery",
  name: "Entrega dos arquivos do projeto",
  price: 0,
  description: "Disponibilização dos componentes contratados e combinados para entrega.",
  why: "O formato de entrega e os acessos precisam ser definidos no contrato. Receber arquivos não mantém servidores, domínio, banco ou serviços de terceiros funcionando automaticamente.",
  includes: ["Frontend e backend que façam parte do escopo", "Código-fonte e configurações acordadas", "Documentação disponível", "Credenciais pertencentes ao cliente"],
  needed: "Quando você deseja receber os componentes do projeto e administrar a operação.",
  fallback: "No modelo gerenciado, o acesso e a operação são definidos conforme o contrato.",
};

export const faqs = [
  { question: "Quanto custa um site?", answer: "Uma landing page simples pode partir de cerca de R$ 3.000 nesta simulação. O valor muda conforme conteúdo, páginas, funcionalidades, integrações e infraestrutura." },
  { question: "Por que uma página de login custa mais?", answer: "Porque normalmente precisa conversar com o backend, validar credenciais, controlar sessões e proteger áreas privadas. A tela é apenas uma parte do trabalho." },
  { question: "Preciso contratar hospedagem?", answer: "Todo projeto publicado precisa estar disponível em algum serviço. Você pode contratar a hospedagem conosco ou administrar uma opção compatível." },
  { question: "O domínio está incluso?", answer: "Não automaticamente. O registro costuma ser pago anualmente ao fornecedor e depende do nome escolhido. A estimativa aparece separada." },
  { question: "Posso hospedar em outro servidor?", answer: "Sim, desde que a infraestrutura seja compatível com as necessidades do projeto e os acessos estejam disponíveis." },
  { question: "Posso receber os arquivos?", answer: "A entrega pode ser combinada no contrato. Ela não inclui hospedagem contínua nem serviços de terceiros por padrão." },
  { question: "Todo projeto precisa de banco de dados ou API?", answer: "Não. Um site informativo pode funcionar sem banco próprio; contas, pedidos e dados que precisam ser guardados normalmente exigem armazenamento e lógica de backend." },
  { question: "A manutenção é obrigatória?", answer: "Não. É opcional quando você consegue administrar a infraestrutura e compatibilidade do projeto. O modelo deve ser definido conforme a necessidade." },
  { question: "O orçamento do simulador é definitivo?", answer: "Não. É uma referência para organizar requisitos. O orçamento final depende de analisar o escopo, as integrações, a infraestrutura e outros detalhes." },
  { question: "Posso contratar apenas o backend?", answer: "Sim. O modo “Somente API + banco” estima uma parte do projeto para quem já tem interface ou infraestrutura própria." },
  { question: "Já tenho servidor, posso utilizá-lo?", answer: "Sim. Escolha “Já tenho servidor” e marque somente os serviços que ainda precisa contratar. A compatibilidade será avaliada na análise do projeto." },
];

export const defaults = {
  project: "institutional",
  pages: ["home"],
  features: [],
  infrastructure: [],
  maintenance: [],
  scenario: "complete",
  delivery: false,
};